import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SettingsService extends ChangeNotifier {
  static final SettingsService _instance = SettingsService._internal();
  factory SettingsService() => _instance;
  SettingsService._internal();

  bool _isDarkMode = false;
  String _languageCode = 'TM'; // Default to Turkmen

  bool get isDarkMode => false;
  String get languageCode => _languageCode;

  Future<void> init() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      _isDarkMode = prefs.getBool('is_dark_mode') ?? false;
      _languageCode = prefs.getString('language_code') ?? 'TM';
    } catch (e) {
      debugPrint('Error initializing SettingsService: $e');
    }
  }

  Future<void> toggleTheme(bool value) async {
    _isDarkMode = value;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('is_dark_mode', _isDarkMode);
    } catch (e) {
      debugPrint('Error saving theme settings: $e');
    }
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (code != 'TM' && code != 'RU' && code != 'EN') return;
    _languageCode = code;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('language_code', _languageCode);
    } catch (e) {
      debugPrint('Error saving language settings: $e');
    }
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_languageCode]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'TM': {
      'profile': 'Profil',
      'guest_title': 'Hasabyňyza giriň',
      'guest_subtitle': 'Sargytlaryňyzy yzarlamak we profil sazlamalaryňyzy üýtgetmek üçin giriň.',
      'login': 'Giriş',
      'logout': 'Ulgamdan çykmak',
      'logout_snack': 'Ulgamdan çykyldy',
      'account_id': 'Hasap ID',
      'role': 'Roly',
      'admin_panel': 'Müdirlik Paneli',
      'news': 'Täzelikler',
      'my_orders': 'Sargytlarym',
      'security': 'Howpsuzlyk',
      'theme': 'Tema',
      'theme_dark': 'Gije',
      'theme_light': 'Gündiz',
      'language': 'Dil',
      'change_password': 'Parolyňyzy üýtgediň',
      'old_password': 'Köne parol',
      'old_password_hint': 'Häzirki parolyňyz',
      'new_password': 'Täze parol',
      'new_password_hint': 'Minimal 6 simwol',
      'confirm_password': 'Täze paroly tassyklamak',
      'confirm_password_hint': 'Paroly gaýtadan ýazyň',
      'save_password': 'Paroly sakla',
      'password_changed_success': 'Paroluňyz üstünlikli çalşyldy!',
      'error_old_password': 'Köne paroluňyzy giriziň',
      'error_new_password': 'Täze paroly giriziň',
      'error_new_password_len': 'Parol azyndan 6 simwol bolmaly',
      'error_confirm_password': 'Täze paroly tassyklamak hökman',
      'error_password_match': 'Parollar gabat gelmedi',
      'loading': 'Ýüklenýär...',
      'no_news': 'Täzelik ýok.',
      'read_more': 'Dowamyny oka',
      'no_orders': 'Siziň entek hiç hili sargydyňyz ýok.',
      'order_id': 'Sargyt ID',
      'date': 'Sene',
      'total_amount': 'Jemi baha',
      'status': 'Ýagdaýy',
      'status_pending': 'Garaşylýar',
      'status_completed': 'Tamamlandy',
      'status_cancelled': 'Ýatyryldy',
      'video_tab': 'Wideo',
      'photo_tab': 'Surat',
      'book_tab': 'Sargyt',
      'profile_tab': 'Profil',
      'home_tab': 'Baş sahypa',
      'categories_tab': 'Kategoriýalar',
      'cart_tab': 'Sebet',
      'videos_tab': 'Wideolar',
      'photos_tab': 'Suratlar',
      'gifts_tab': 'Sowgatlar',
      'try_again': 'Täzeden synanyşyň',
      'no_videos': 'Wideo tapylmady',
      'no_photos': 'Surat tapylmady',
      'error_videos': 'Wideolary ýükläp bolmady',
      'error_photos': 'Suratlary ýükläp bolmady',
      'error_campaigns': 'Aksiýalary ýükläp bolmady',
      'no_campaigns': 'Agza bolmaly aksiýalar tapylmady',
      'join': 'Gatnaş',
      'joined': 'Gatnaşyldy',
      'ended': 'Tamamlandy',
      'welcome_promos': 'AKSIÝALAR WE SOWGATLAR',
      'welcome_gifts': 'Sowgatlar we Mümkinçilikler',
      'promos_desc': 'Doganlar programmasy tarapyndan agzalar üçin ýörite bäsleşikler we sowgatlar.',
      'what_given': 'Näme berilýär:',
      'what_do': 'Näme ýerine ýetirmeli:',
      'posted_date': 'Bildiriş goýlan güni:',
      'join_promo': 'Aksiýa gatnaşmak',
      'full_name': 'Adyňyz we familiýaňyz *',
      'phone_number': 'Telefon belgiňiz *',
      'email': 'E-poçta',
      'note': 'Goşmaça bellik',
      'write_note': 'Bellik ýazyň...',
      'login_required_join': 'Aksiýa gatnaşmak üçin ilki hasabyňyza giriň.',
      'success_joined': 'Üstünlikli gatnaşdyňyz!',
      'write_name': 'Adyňyzy ýazyň',
      'write_phone': 'Telefon belgiňizi ýazyň',
      'categories': 'Kategoriýalar',
      'featured_products': 'Saýlama Harytlar',
      'on_sale': 'Arzanlaşykdaky',
      'top_brands': 'Esasy Brendler',
      'search_product': 'Haryt gözle...',
      'brands': 'Brendler',
      'price_range': 'Baha aralygy (TMT)',
      'rating': 'Reýting',
      'only_in_stock': 'Diňe ammarda bar',
      'on_sale_products': 'Arzanlaşykdaky harytlar',
      'clear_filter': 'Arassala',
      'filters': 'Filterler',
      'search_btn': 'Gözle',
      'view_all': 'Hemmesini gör',
      'no_products_found': 'Haryt tapylmady',
      'my_cart': 'Sebedim',
      'order_info': 'Sargyt maglumatlary',
      'cart_empty': 'Sebediňiz boş',
      'cart_empty_subtitle': 'Entek hiç haryt goşmadyňyz. Häzir söwda edip başlaň!',
      'continue_shopping_btn': 'Söwda dowam et',
      'total_items_label': 'Jemi harytlar:',
      'pcs': ' sany',
      'total_price_label': 'Umumy baha:',
      'checkout_btn': 'Sargamak',
      'clear_cart': 'SEBEDI ARASSALA',
      'order_details_title': 'Sargyt etmek üçin maglumatlar',
      'order_details_subtitle': 'Sargydyňyzy tassyklamak üçin maglumatlary dolduryň. Biz gysga wagtda habarlaşarys.',
      'full_name_label': 'Doly adyňyz *',
      'name_placeholder': 'At-familiýaňyz',
      'write_name_error': 'Adyňyzy ýazyň',
      'phone_label': 'Telefon belgiňiz *',
      'write_phone_error': 'Telefon belgiňizi ýazyň',
      'phone_format_error': 'Telefon belgi +993 bilen başlamaly',
      'note_label': 'Goşmaça bellik',
      'note_placeholder': 'Sargyt barada bellikleriňiz...',
      'order_summary': 'Sargyt jemlemesi',
      'product_count_label': 'Haryt sany:',
      'place_order_btn': 'Sargyt etmek',
      'order_received_title': 'Sargyt kabul edildi!',
      'order_received_body_prefix': 'Sargydyňyz üstünlikli kabul edildi! Sargyt belgisi: #',
      'order_received_body_suffix': '.\nBiz ýakyn wagtda habarlaşarys.',
      'close_btn': 'Ýap',
      'error_prefix': 'Ýalňyşlyk ýüze çykdy: ',
      'cart_remove_snack': 'sebetden aýryldy!',
      'cart_add_snack': 'sebede goşuldy!',
      'remove_btn': 'Aýyr',
      'add_to_cart_btn': 'Sebede goş',
      'welcome': 'Hoş geldiňiz!',
      'what_looking_for': 'Aşakdaky bölümler bilen dowam ediň',
      'admin_panel_card_title': 'Müdirlik paneli',
      'admin_panel_card_subtitle': 'Ulgamy dolandyrmak',
      'products_card_title': 'Harytlar',
      'products_card_subtitle': 'Suratçylyk ugruna degişli harytlar',
      'studio_card_title': 'Foto studio',
      'studio_card_subtitle': 'Surat we wideo düşürmek',
      'promo_card_title': 'Sowgatlar',
      'promo_card_subtitle': 'Sowgatlar, bäsleşikler we aksiýalar',
      'about_us': 'Biz barada',
      'about_hero_tagline': 'Siziň durmuşyňyzyň dury pursatlary',
      'about_hero_desc': 'Mary şäherinde ýokary hilli foto apparatlaryň söwdasy we professional surat hyzmatlaryny hödürleýän merkez.',
      'about_services_title': 'Esasy hyzmatlarymyz',
      'about_service1_title': 'Foto apparatlar',
      'about_service1_desc': 'Dünä belli brendleriň (Canon, Nikon, Sony) iň soňky modeldäki foto apparatlarynyň söwdasy.',
      'about_service2_title': 'Gurluşlar we Enjamlar',
      'about_service2_desc': 'Obýektiwler, ştatiwler, yşyklandyryş enjamlary we ähli görnüşli foto-aksessuarlar.',
      'about_service3_title': 'Surat hyzmatlary',
      'about_service3_desc': 'Professional studio suratlary, toý-dabaralaryň we dürli ýatdan çykmajak pursatlaryň surata düşürilmegi.',
      'about_details_title': 'Biz barada has giňişleýin',
      'about_experience_badge': 'Ýyllyk Tejribe',
      'about_address_label': 'Biziň salgymyz',
      'about_address_val': 'Mary şäheri, Mollanepes kelte köçesi',
      'about_contact_label': 'Habarlaşmak üçin',
      'about_email_label': 'Email salgymyz',
      'about_work_hours_label': 'Iş wagtlarymyz',
      'about_work_hours_val': 'Her gün: 08:00 - 19:00',
      'about_why_choose_us': 'Näme üçin bizi saýlamaly?',
      'about_why1_title': 'Original Harytlar',
      'about_why1_desc': 'Diňe dünýä belli brendleriň hakyky önümleri.',
      'about_why2_title': 'Amatly Baha',
      'about_why2_desc': 'Bazaryň iň amatly we elýeterli bahalary.',
      'about_why3_title': 'Kepillik',
      'about_why3_desc': 'Satan ähli harytlarymyza doly kepillik berýäris.',
      'about_why4_title': 'Professional Maslahat',
      'about_why4_desc': 'Enjam saýlamakda hünärmen kömegi.',
    },
    'RU': {
      'profile': 'Профиль',
      'guest_title': 'Войдите в аккаунт',
      'guest_subtitle': 'Войдите, чтобы отслеживать свои заказы и изменять настройки профиля.',
      'login': 'Войти',
      'logout': 'Выйти из системы',
      'logout_snack': 'Выход выполнен',
      'account_id': 'ID Аккаунта',
      'role': 'Роль',
      'admin_panel': 'Панель администратора',
      'news': 'Новости',
      'my_orders': 'Мои заказы',
      'security': 'Безопасность',
      'theme': 'Тема',
      'theme_dark': 'Ночь',
      'theme_light': 'День',
      'language': 'Язык',
      'change_password': 'Изменить пароль',
      'old_password': 'Старый пароль',
      'old_password_hint': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'new_password_hint': 'Минимум 6 символов',
      'confirm_password': 'Подтверждение нового пароля',
      'confirm_password_hint': 'Повторите пароль',
      'save_password': 'Сохранить пароль',
      'password_changed_success': 'Ваш пароль успешно изменен!',
      'error_old_password': 'Введите старый пароль',
      'error_new_password': 'Введите новый пароль',
      'error_new_password_len': 'Пароль должен быть не менее 6 символов',
      'error_confirm_password': 'Подтвердите новый пароль',
      'error_password_match': 'Пароли не совпадают',
      'loading': 'Загрузка...',
      'no_news': 'Нет новостей.',
      'read_more': 'Читать далее',
      'no_orders': 'У вас пока нет заказов.',
      'order_id': 'ID Заказа',
      'date': 'Дата',
      'total_amount': 'Итоговая сумма',
      'status': 'Статус',
      'status_pending': 'В ожидании',
      'status_completed': 'Завершен',
      'status_cancelled': 'Отменен',
      'video_tab': 'Видео',
      'photo_tab': 'Фото',
      'book_tab': 'Забронировать',
      'profile_tab': 'Профиль',
      'home_tab': 'Главная',
      'categories_tab': 'Категории',
      'cart_tab': 'Корзина',
      'videos_tab': 'Видео',
      'photos_tab': 'Фото',
      'gifts_tab': 'Подарки',
      'try_again': 'Попробовать снова',
      'no_videos': 'Нет видео',
      'no_photos': 'Нет фото',
      'error_videos': 'Не удалось загрузить видео',
      'error_photos': 'Не удалось загрузить фото',
      'error_campaigns': 'Не удалось загрузить акции',
      'no_campaigns': 'Нет активных акций',
      'join': 'Участвовать',
      'joined': 'Участвует',
      'ended': 'Завершено',
      'welcome_promos': 'АКЦИИ И ПОДАРКИ',
      'welcome_gifts': 'Подарки и Возможности',
      'promos_desc': 'Специальные конкурсы, подарки и акции для пользователей приложения Doganlar.',
      'what_given': 'Что дарят:',
      'what_do': 'Что нужно сделать:',
      'posted_date': 'Дата публикации:',
      'join_promo': 'Участие в акции',
      'full_name': 'Имя и фамилия *',
      'phone_number': 'Номер телефона *',
      'email': 'Электронная почта',
      'note': 'Примечание',
      'write_note': 'Напишите примечание...',
      'login_required_join': 'Войдите в аккаунт, чтобы принять участие.',
      'success_joined': 'Успешное участие!',
      'write_name': 'Введите имя',
      'write_phone': 'Введите номер телефона',
      'categories': 'Категории',
      'featured_products': 'Популярные товары',
      'on_sale': 'Со скидкой',
      'top_brands': 'Основные бренды',
      'search_product': 'Поиск товара...',
      'brands': 'Бренды',
      'price_range': 'Диапазон цен (TMT)',
      'rating': 'Рейтинг',
      'only_in_stock': 'Только в наличии',
      'on_sale_products': 'Товары со скидкой',
      'clear_filter': 'Очистить',
      'filters': 'Фильтры',
      'search_btn': 'Поиск',
      'view_all': 'Показать все',
      'no_products_found': 'Товары не найдены',
      'my_cart': 'Моя корзина',
      'order_info': 'Информация о заказе',
      'cart_empty': 'Ваша корзина пуста',
      'cart_empty_subtitle': 'Вы еще не добавили ни одного товара. Начните делать покупки прямо сейчас!',
      'continue_shopping_btn': 'Продолжить покупки',
      'total_items_label': 'Всего товаров:',
      'pcs': ' шт',
      'total_price_label': 'Итоговая цена:',
      'checkout_btn': 'Оформить заказ',
      'clear_cart': 'ОЧИСТИТЬ КОРЗИНУ',
      'order_details_title': 'Информация для заказа',
      'order_details_subtitle': 'Заполните информацию для подтверждения заказа. Мы свяжемся с вами в ближайшее время.',
      'full_name_label': 'Ваше полное имя *',
      'name_placeholder': 'Ваше имя и фамилия',
      'write_name_error': 'Введите ваше имя',
      'phone_label': 'Номер телефона *',
      'write_phone_error': 'Введите номер телефона',
      'phone_format_error': 'Номер телефона должен начинаться с +993',
      'note_label': 'Дополнительное примечание',
      'note_placeholder': 'Ваши примечания к заказу...',
      'order_summary': 'Итоги заказа',
      'product_count_label': 'Количество:',
      'place_order_btn': 'Сделать заказ',
      'order_received_title': 'Заказ принят!',
      'order_received_body_prefix': 'Ваш заказ успешно принят! Номер заказа: #',
      'order_received_body_suffix': '.\nМы свяжемся с вами в ближайшее время.',
      'close_btn': 'Закрыть',
      'error_prefix': 'Произошла ошибка: ',
      'cart_remove_snack': 'удалено из корзины!',
      'cart_add_snack': 'добавлено в корзину!',
      'remove_btn': 'Удалить',
      'add_to_cart_btn': 'В корзину',
      'welcome': 'Добро пожаловать!',
      'what_looking_for': 'Продолжайте с разделами ниже',
      'admin_panel_card_title': 'Панель администратора',
      'admin_panel_card_subtitle': 'Управление системой',
      'products_card_title': 'Товары',
      'products_card_subtitle': 'Товары для фотографии и видеосъемки',
      'studio_card_title': 'Фотостудия',
      'studio_card_subtitle': 'Фото и видеосъемка',
      'promo_card_title': 'Подарки',
      'promo_card_subtitle': 'Подарки, конкурсы и акции',
      'about_us': 'О нас',
      'about_hero_tagline': 'Яркие моменты вашей жизни',
      'about_hero_desc': 'Центр в г. Мары, предлагающий продажу качественных фотоаппаратов и профессиональные фотоуслуги.',
      'about_services_title': 'Наши основные услуги',
      'about_service1_title': 'Фотоаппараты',
      'about_service1_desc': 'Продажа последних моделей фотоаппаратов мировых брендов (Canon, Nikon, Sony).',
      'about_service2_title': 'Оборудование и техника',
      'about_service2_desc': 'Объективы, штативы, осветительное оборудование и все виды фотоаксессуаров.',
      'about_service3_title': 'Фотоуслуги',
      'about_service3_desc': 'Профессиональная студийная съемка, съемка свадеб и различных незабываемых моментов.',
      'about_details_title': 'Подробнее о нас',
      'about_experience_badge': 'Лет Опыта',
      'about_address_label': 'Наш адрес',
      'about_address_val': 'г. Мары, улица Молланепеса',
      'about_contact_label': 'Для связи',
      'about_email_label': 'Наш Email',
      'about_work_hours_label': 'Часы работы',
      'about_work_hours_val': 'Каждый день: 08:00 - 19:00',
      'about_why_choose_us': 'Почему выбирают нас?',
      'about_why1_title': 'Оригинальные товары',
      'about_why1_desc': 'Только оригинальная продукция мировых брендов.',
      'about_why2_title': 'Доступные цены',
      'about_why2_desc': 'Самые выгодные и доступные цены на рынке.',
      'about_why3_title': 'Гарантия',
      'about_why3_desc': 'Мы даем полную гарантию на все проданные товары.',
      'about_why4_title': 'Профессиональная консультация',
      'about_why4_desc': 'Помощь специалистов в выборе оборудования.',
    },
    'EN': {
      'profile': 'Profile',
      'guest_title': 'Login to your account',
      'guest_subtitle': 'Log in to track your orders and change your profile settings.',
      'login': 'Login',
      'logout': 'Logout',
      'logout_snack': 'Logged out successfully',
      'account_id': 'Account ID',
      'role': 'Role',
      'admin_panel': 'Admin Dashboard',
      'news': 'News',
      'my_orders': 'My Orders',
      'security': 'Security',
      'theme': 'Theme',
      'theme_dark': 'Night',
      'theme_light': 'Day',
      'language': 'Language',
      'change_password': 'Change Password',
      'old_password': 'Old Password',
      'old_password_hint': 'Your current password',
      'new_password': 'New Password',
      'new_password_hint': 'Minimum 6 characters',
      'confirm_password': 'Confirm New Password',
      'confirm_password_hint': 'Retype password',
      'save_password': 'Save Password',
      'password_changed_success': 'Password changed successfully!',
      'error_old_password': 'Enter your old password',
      'error_new_password': 'Enter your new password',
      'error_new_password_len': 'Password must be at least 6 characters',
      'error_confirm_password': 'Confirm your new password',
      'error_password_match': 'Passwords do not match',
      'loading': 'Loading...',
      'no_news': 'No news available.',
      'read_more': 'Read more',
      'no_orders': 'You do not have any orders yet.',
      'order_id': 'Order ID',
      'date': 'Date',
      'total_amount': 'Total Amount',
      'status': 'Status',
      'status_pending': 'Pending',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'video_tab': 'Video',
      'photo_tab': 'Photo',
      'book_tab': 'Book',
      'profile_tab': 'Profile',
      'home_tab': 'Home',
      'categories_tab': 'Categories',
      'cart_tab': 'Cart',
      'videos_tab': 'Videos',
      'photos_tab': 'Photos',
      'gifts_tab': 'Gifts',
      'try_again': 'Try again',
      'no_videos': 'No videos yet',
      'no_photos': 'No photos yet',
      'error_videos': 'Could not load videos',
      'error_photos': 'Could not load photos',
      'error_campaigns': 'Could not load campaigns',
      'no_campaigns': 'No active campaigns yet',
      'join': 'Join',
      'joined': 'Joined',
      'ended': 'Ended',
      'welcome_promos': 'Promotions & Giveaways',
      'welcome_gifts': 'Gifts & Opportunities',
      'promos_desc': 'Special contests, gifts, and promotions for Doganlar app users.',
      'what_given': 'What is given:',
      'what_do': 'What to perform:',
      'posted_date': 'Posted date:',
      'join_promo': 'Join Promotion',
      'full_name': 'Full name *',
      'phone_number': 'Phone number *',
      'email': 'Email',
      'note': 'Additional note',
      'write_note': 'Write a note...',
      'login_required_join': 'Login required to join promotion.',
      'success_joined': 'Successfully joined!',
      'write_name': 'Write your name',
      'write_phone': 'Write your phone number',
      // Commerce translation keys
      'categories': 'Categories',
      'featured_products': 'Featured Products',
      'on_sale': 'On Sale',
      'top_brands': 'Top Brands',
      'search_product': 'Search product...',
      'brands': 'Brands',
      'price_range': 'Price range (TMT)',
      'rating': 'Rating',
      'only_in_stock': 'Only in stock',
      'on_sale_products': 'Products on sale',
      'clear_filter': 'Clear',
      'filters': 'Filters',
      'search_btn': 'Search',
      'view_all': 'View all',
      'no_products_found': 'No products found',
      'my_cart': 'My Cart',
      'order_info': 'Order Information',
      'cart_empty': 'Your cart is empty',
      'cart_empty_subtitle': 'You haven\'t added any products yet. Start shopping now!',
      'continue_shopping_btn': 'Continue shopping',
      'total_items_label': 'Total items:',
      'pcs': ' pcs',
      'total_price_label': 'Total price:',
      'checkout_btn': 'Checkout',
      'clear_cart': 'CLEAR CART',
      'order_details_title': 'Order details',
      'order_details_subtitle': 'Fill in the information to confirm your order. We will contact you shortly.',
      'full_name_label': 'Your full name *',
      'name_placeholder': 'Your full name',
      'write_name_error': 'Write your name',
      'phone_label': 'Phone number *',
      'write_phone_error': 'Write your phone number',
      'phone_format_error': 'Phone number must start with +993',
      'note_label': 'Additional note',
      'note_placeholder': 'Your notes about the order...',
      'order_summary': 'Order summary',
      'product_count_label': 'Product count:',
      'place_order_btn': 'Place order',
      'order_received_title': 'Order received!',
      'order_received_body_prefix': 'Your order has been successfully placed! Order ID: #',
      'order_received_body_suffix': '.\nWe will contact you shortly.',
      'close_btn': 'Close',
      'error_prefix': 'An error occurred: ',
      'cart_remove_snack': 'removed from cart!',
      'cart_add_snack': 'added to cart!',
      'remove_btn': 'Remove',
      'add_to_cart_btn': 'Add to cart',
      'welcome': 'Welcome!',
      'what_looking_for': 'Continue with the sections below',
      'admin_panel_card_title': 'Admin panel',
      'admin_panel_card_subtitle': 'System management',
      'products_card_title': 'Products',
      'products_card_subtitle': 'Photography and videography goods',
      'studio_card_title': 'Photo studio',
      'studio_card_subtitle': 'Photo and video shooting',
      'promo_card_title': 'Gifts',
      'promo_card_subtitle': 'Gifts, contests and promotions',
      'about_us': 'About Us',
      'about_hero_tagline': 'Clear moments of your life',
      'about_hero_desc': 'A center in Mary city offering sales of high-quality cameras and professional photo services.',
      'about_services_title': 'Our Core Services',
      'about_service1_title': 'Cameras',
      'about_service1_desc': 'Sales of the latest camera models from world-famous brands (Canon, Nikon, Sony).',
      'about_service2_title': 'Gear & Equipment',
      'about_service2_desc': 'Lenses, tripods, lighting equipment, and all types of photo accessories.',
      'about_service3_title': 'Photo Services',
      'about_service3_desc': 'Professional studio shooting, weddings and various unforgettable moments shooting.',
      'about_details_title': 'About Us In Detail',
      'about_experience_badge': 'Years of Experience',
      'about_address_label': 'Our Address',
      'about_address_val': 'Mary city, Mollanepes street',
      'about_contact_label': 'Contact Us',
      'about_email_label': 'Our Email',
      'about_work_hours_label': 'Work Hours',
      'about_work_hours_val': 'Every day: 08:00 - 19:00',
      'about_why_choose_us': 'Why Choose Us?',
      'about_why1_title': 'Original Products',
      'about_why1_desc': 'Only authentic products from world-famous brands.',
      'about_why2_title': 'Reasonable Price',
      'about_why2_desc': 'The most reasonable and affordable prices on the market.',
      'about_why3_title': 'Warranty',
      'about_why3_desc': 'We offer a full warranty on all sold products.',
      'about_why4_title': 'Professional Advice',
      'about_why4_desc': 'Specialist assistance in selecting equipment.',
    }
  };
}
